import re
import random
import unidecode
from nltk.tokenize import sent_tokenize


f = open("/home/dang/Downloads/test")
data = f.read()
# print(data)
# sentences = list(sent_tokenize(data))
n_data = data.split()

def autoSinhLoiVM(text):
    text = re.sub('lũng', 'nũng', text)
    text = re.sub('lũ', 'nũ', text)
    text = re.sub('lệch', 'nệch', text)
    text = re.sub('lẽo', 'nẽo', text)
    text = re.sub('lên', 'nên', text)
    text = re.sub('lưu', 'nưu', text)
    text = re.sub('lui', 'nui', text)
    text = re.sub('lọc', 'nọc', text)
    text = re.sub('lộng', 'nộng', text)
    text = re.sub('làng', 'nàng', text)
    text = re.sub('lay', 'nay', text)
    text = re.sub('liên', 'niên', text)
    text = re.sub('lạnh', 'nạnh', text)
    text = re.sub('lẫn', 'nẫn', text)
    text = re.sub('lũy', 'nũy', text)

    text = re.sub('nam', 'lam', text)
    text = re.sub('này', 'lày', text)
    text = re.sub('niệm', 'liệm', text)
    text = re.sub('nền', 'lền', text)
    text = re.sub('nạt', 'lạt', text)
    text = re.sub('náo', 'láo', text)
    text = re.sub('nói', 'lói', text)
    text = re.sub('nào', 'lào', text)
    text = re.sub('nồi', 'lồi', text)
    text = re.sub('nổ', 'lổ', text)
    text = re.sub('nắng', 'lắng', text)
    text = re.sub('nơi', 'lơi', text)
    text = re.sub('nới', 'lới', text)
    text = re.sub('năm', 'lăm', text)

    text = re.sub('chứng', 'trứng', text)
    text = re.sub('chợ', 'trợ', text)
    text = re.sub('chua', 'trua', text)
    text = re.sub('chị', 'trị', text)
    text = re.sub('chả', 'trả', text)
    text = re.sub('cháu', 'tráu', text)
    text = re.sub('chèn', 'trèn', text)
    text = re.sub('chỗ', 'trỗ', text)
    text = re.sub('chạm', 'trạm', text)
    text = re.sub('chiến', 'triến', text)
    text = re.sub('chắm', 'trắm', text)
    text = re.sub('chừng', 'trừng', text)
    text = re.sub('chuyền', 'truyền', text)
    text = re.sub('chuối', 'truối', text)
    text = re.sub('châm', 'trâm', text)
    text = re.sub('chưa', 'trưa', text)
    text = re.sub('chọc', 'trọc', text)

    text = re.sub('triệt', 'chiệt', text)
    text = re.sub('tru', 'chu', text)
    text = re.sub('trơn', 'chơn', text)
    text = re.sub('trắng', 'chắng', text)
    text = re.sub('trĩu', 'chĩu', text)
    text = re.sub('trệt', 'chệt', text)
    text = re.sub('trù', 'chù', text)
    text = re.sub('trụ', 'chụ', text)
    text = re.sub('tránh', 'chánh', text)
    text = re.sub('trẻ', 'chẻ', text)
    text = re.sub('trân', 'chân', text)
    text = re.sub('trật', 'chật', text)
    text = re.sub('trống', 'chống', text)
    text = re.sub('trữ', 'chữ', text)
    text = re.sub('trạng', 'chạng', text)
    text = re.sub('trú', 'chú', text)
    text = re.sub('trải', 'chải', text)
    text = re.sub('trong', 'chong', text)

    text = re.sub('sạn', 'xạn', text)
    text = re.sub('sẻ', 'xẻ', text)
    text = re.sub('sắp', 'xắp', text)
    text = re.sub('sộ', 'xộ', text)
    text = re.sub('siêu', 'xiêu', text)
    text = re.sub('sợ', 'xợ', text)
    text = re.sub('suôn', 'xuôn', text)
    text = re.sub('sướng', 'xướng', text)
    text = re.sub('siêm', 'xiêm', text)
    text = re.sub('sôi', 'xôi', text)
    text = re.sub('sam', 'xam', text)
    text = re.sub('sấm', 'xấm', text)
    text = re.sub('suông', 'xuông', text)
    text = re.sub('sắc', 'xắc', text)
    text = re.sub('sụn', 'xụn', text)
    text = re.sub('sài', 'xài', text)
    text = re.sub('sảo', 'xảo', text)
    text = re.sub('sếp', 'xếp', text)

    text = re.sub('xuyến', 'suyến', text)
    text = re.sub('xèo', 'sèo', text)
    text = re.sub('xóa', 'sóa', text)
    text = re.sub('xòe', 'sòe', text)
    text = re.sub('xóc', 'sóc', text)
    text = re.sub('xang', 'sang', text)
    text = re.sub('xứ', 'sứ', text)
    text = re.sub('xảo', 'sảo', text)
    text = re.sub('xây', 'sây', text)
    text = re.sub('xoay', 'soay', text)
    text = re.sub('xâu', 'sâu', text)
    text = re.sub('xe', 'se', text)
    text = re.sub('xong', 'song', text)
    text = re.sub('xanh', 'sanh', text)
    text = re.sub('xuốn', 'suốn', text)
    text = re.sub('xử', 'sử', text)
    text = re.sub('xã', 'sã', text)
    text = re.sub('xuông', 'suông', text)

    text = re.sub('ngã', 'ngá', text)
    text = re.sub('lũ', 'lú', text)
    text = re.sub('sĩ', 'sí', text)
    text = re.sub('lẽo', 'léo', text)
    text = re.sub('sữa', 'súa', text)
    text = re.sub('võ', 'vó', text)
    text = re.sub('bản', 'bạn', text)
    text = re.sub('đổi', 'đội', text)
    text = re.sub('não', 'náo', text)
    text = re.sub('mẩu', 'mậu', text)
    text = re.sub('bổ', 'bộ', text)
    text = re.sub('tỉ', 'tị', text)
    text = re.sub('sổm', 'sộm', text)
    text = re.sub('dở', 'dợ', text)
    text = re.sub('gửi', 'gựi', text)
    text = re.sub('nhẩm', 'nhậm', text)
    text = re.sub('rõng', 'rống', text)
    text = re.sub('phở', 'phợ', text)
    text = re.sub('tuôi', 'tui', text)
    text = re.sub('vui', 'zui', text)
    text = re.sub('vẻ', 'zẻ', text)
    text = re.sub('vời', 'zời', text)

    return text
def autoSinhLoiDM(text):
    text = re.sub('hôi', 'hooi', text)
    text = re.sub('kiềm', 'kieemf', text)
    text = re.sub('phiếu', 'phieeus', text)
    text = re.sub('cuối', 'cuoois', text)
    text = re.sub('mạch', 'machj', text)
    text = re.sub('hiền', 'hieenf', text)
    text = re.sub('dồn', 'doonf', text)
    text = re.sub('kèm', 'kemf', text)
    text = re.sub('đang', 'ddang', text)
    text = re.sub('tính', 'tinhs', text)
    text = re.sub('bát', 'bats', text)
    text = re.sub('bạn', 'banj', text)
    text = re.sub('nghiện', 'nghieenj', text)
    text = re.sub('toán', 'toans', text)
    text = re.sub('thực', 'thuwcj', text)

    text = re.sub('căn', 'canw', text)
    text = re.sub('khẩn', 'khaanr', text)
    text = re.sub('đợi', 'ddowij', text)
    text = re.sub('khướu', 'khuowus', text)
    text = re.sub('buôn', 'buoon', text)
    text = re.sub('thiệt', 'thieetj', text)
    text = re.sub('gừng', 'guwngf', text)
    text = re.sub('bức', 'buwcs', text)
    text = re.sub('kiểu', 'kieeur', text)
    text = re.sub('nguồn', 'nguoonf', text)
    text = re.sub('phẳng', 'phawngr', text)
    text = re.sub('lĩnh', 'linhx', text)
    text = re.sub('thẫm', 'thaamx', text)
    text = re.sub('nhưng', 'nhuwng', text)

    text = re.sub('dũng', 'dungx', text)
    text = re.sub('võ', 'vox', text)
    text = re.sub('nghiêng', 'nghieeng', text)
    text = re.sub('quốc', 'quoocs', text)
    text = re.sub('đức', 'dduwcs', text)
    text = re.sub('tiểu', 'tieeur', text)
    text = re.sub('phẳng', 'phawngr', text)
    text = re.sub('phản', 'phanr', text)
    text = re.sub('âm', 'aam', text)
    text = re.sub('mập', 'maapj', text)
    text = re.sub('phông', 'phoong', text)
    text = re.sub('giấy', 'giaays', text)
    text = re.sub('thần', 'thaanf', text)
    text = re.sub('huyền', 'huyeenf', text)
    text = re.sub('hiểm', 'hieemr', text)
    text = re.sub('nhái', 'nhais', text)
    text = re.sub('đỗ', 'ddoox', text)

    text = re.sub('sống', 'soongs', text)
    text = re.sub('dựng', 'duwngj', text)
    text = re.sub('miền', 'mieenf', text)
    text = re.sub('đảm', 'ddamr', text)
    text = re.sub('khỏe', 'khoer', text)
    text = re.sub('tịch', 'tichj', text)
    text = re.sub('muốn', 'muoons', text)
    text = re.sub('điều', 'ddieeuf', text)
    text = re.sub('ruộng', 'ruoongj', text)
    text = re.sub('bất', 'baats', text)
    text = re.sub('đổi', 'ddooir', text)
    text = re.sub('duyên', 'duyeen', text)
    text = re.sub('hoảng', 'hoangr', text)
    text = re.sub('hải', 'hair', text)
    text = re.sub('đêm', 'ddeem', text)
    text = re.sub('khánh', 'khanhs', text)
    text = re.sub('nhượng', 'nhuowngj', text)
    text = re.sub('chuẩn', 'chuaanr', text)

    return text

# for s in sentences[:]:
#     sentences.remove(s)
#     s = s.lower()
#     s = s.strip()
#     s = autoSinhLoi(s)
#     sentences.append(s)
#
# print(sentences)
for d in n_data[:]:
    n_data.remove(d)
    d = d.lower()
    # d = autoSinhLoiVM(d)
    # d = autoSinhLoiDM(d)
    d = unidecode.unidecode(d)
    n_data.append(d)

n_data =' '.join(n_data)
print(n_data)
